import time, json, random
import logging
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.common.exceptions import TimeoutException
from selenium.common.exceptions import WebDriverException
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait, Select
from datetime import datetime
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support import expected_conditions as EC
from random import choice
from random import randint
import re
from sys import exit
from selenium.webdriver import ActionChains
from selenium.webdriver.common.action_chains import ActionChains
import pathlib
from pathlib import Path
import os,pathlib,glob
from sys import platform
import luu_function
from luu_function import local, data, Logging, ValidateFailResultAndSystem,TestCase_LogResult
from luu_function import driver

time.sleep(1)


def CheckPresenceOfAdminsubmenu(domain_name):
    Logging("------------------------------------------------------C. Menu Menu Builder------------------------------------------------------")
    driver.get(domain_name + "/custom_menu")
    #time.sleep(2)
    #driver.refresh()
    time.sleep(6)

    try:
        WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["icon_create_menu"])))
        admin = True
    except WebDriverException:
        admin = False
    return admin


def admin_write_menubuilder(domain_name):
    
    time.sleep(2)  
    Logging("------------------------------------------------------D. Menu Builder------------------------------------------------------")
    #driver.get(domain_name + "/custom_menu/write/")
    #access_menu_menu_builder = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["menu_builder"])))
    #access_menu_menu_builder.click()
    Logging("1. Access Menu Builder successfully")
    Logging("--------------------- Write Menu   ---------------------")

    try:
        click_btn_close_clock_in = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_close_clock_in"])))
        click_btn_close_clock_in.click()
    except WebDriverException:
        Logging("Not show Clock In")

    time.sleep(2)
    click_icon_write_menu = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["icon_create_menu"])))
    click_icon_write_menu .click()
    Logging("1.Click button Create  successfully")
    time.sleep(6)
    btn_cancel_write_menu = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_cancel_menu"])))
    btn_cancel_write_menu.click()
    time.sleep(2)
    Logging("2.Click button Cancel  successfully")
    driver.switch_to.frame(1)
    time.sleep(1)
    click_txt_name_builder = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["name_menu_builder"])))
    click_txt_name_builder.click()
    txtname_clear_builder = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_name_builder"])))
    txtname_clear_builder.clear()
    txtname_clear_builder = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_name_builder"])))
    txtname_clear_builder.send_keys(data["menubuilder"]["name_menu_builder_update"])
    Logging("3. Input Name Menu Builder  successfully")
    click_menu_icon_builder = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["click_menu_icon"])))
    click_menu_icon_builder.click()
    select_icon_builder = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["select_icon"])))
    select_icon_builder.click()
    btn_done_icon_builder = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_done_icon"])))
    btn_done_icon_builder.click()
    Logging("4. Select icon Menu Builder  successfully")
    txt_sub_menu_name = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_sub_menu_name"])))
    txt_sub_menu_name.send_keys(data["menubuilder"]["name_sub_menu"])
    Logging("5. Input Sub Menu Name Builder  successfully")
    click_icon_sub_menu_builder = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["click_icon_sub_menu"])))
    click_icon_sub_menu_builder.click()
    select_icon_sub_menu_builder = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["select_icon_sub_menu"])))
    select_icon_sub_menu_builder.click()
    Logging("6. Select icon Sub Menu Name Builder  successfully")
    time.sleep(1)
    Logging("---   Drag Layout Single Line   --- ")
    single_line_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["single_line_from"])))
    editor_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag"])))
    webdriver.ActionChains(driver).drag_and_drop(single_line_from,editor_to).perform()
    Logging("7.Drag Layout Single Line  successfully")
    time.sleep(1)
    mail_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["email_from"])))
    editor_to_2 = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag_2"])))
    webdriver.ActionChains(driver).drag_and_drop(mail_from,editor_to_2).perform()
    Logging("8.Drag Layout Email  successfully")
    time.sleep(1)
    url_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["url_from_builder"])))
    editor_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag"])))
    webdriver.ActionChains(driver).drag_and_drop(url_from,editor_to).perform()
    Logging("9.Drag Layout URL  successfully")
    time.sleep(1)
    date_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["date_from_builder"])))
    editor_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag_2"])))
    webdriver.ActionChains(driver).drag_and_drop(date_from,editor_to).perform()
    Logging("10.Drag Layout Date  successfully")
    time.sleep(1)
    date_time_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["datetime_from_builder"])))
    editor_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag"])))
    webdriver.ActionChains(driver).drag_and_drop(date_time_from,editor_to).perform()
    Logging("11.Drag Layout Date/Time  successfully")
    time.sleep(1)
    date_range = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["daterange_from_builder"])))
    editor_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag_2"])))
    webdriver.ActionChains(driver).drag_and_drop(date_range,editor_to).perform()
    Logging("11.Drag Date Range  successfully")
    time.sleep(1)
    phone_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["phone_from_builder"])))
    editor_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag"])))
    webdriver.ActionChains(driver).drag_and_drop(phone_from,editor_to).perform()
    time.sleep(1)
    turn_on_input_mask = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["input_mask"])))
    turn_on_input_mask.click()
    time.sleep(1)
    btn_done_input_mask = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_done_input_mask"])))
    btn_done_input_mask.click()
    time.sleep(1)
    Logging("12.Turn On Input Mask successfully")
    Logging("13.Drag Phone  successfully")
    multi_line_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["multi_line_from_builder"])))
    editor_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag_2"])))
    webdriver.ActionChains(driver).drag_and_drop(multi_line_from,editor_to).perform()
    Logging("14.Drag Layout Multi-Line  successfully")
    time.sleep(1)
    multiple_choice_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["multiple_choice_from_builder"])))
    editor_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag"])))
    webdriver.ActionChains(driver).drag_and_drop(multiple_choice_from,editor_to).perform()
    time.sleep(1)
    txt_option1_choice = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_options_1"])))
    txt_option1_choice.clear()
    txt_option1_choice = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_options_1"])))
    txt_option1_choice.send_keys(data["menubuilder"]["name_option1_choice"])
    Logging("15a.Input Option 1  successfully")
    time.sleep(1)
    txt_option1_choice.send_keys(Keys.RETURN)
    txt_option2_choice = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_options_2"])))
    txt_option2_choice.send_keys(data["menubuilder"]["name_option2_choice"])
    txt_option2_choice.send_keys(Keys.RETURN)
    time.sleep(1)
    Logging("15b.Input Option 2  successfully")
    txt_option3_choice = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_options_3"])))
    txt_option3_choice.send_keys(data["menubuilder"]["name_option3_choice"])
    txt_option3_choice.send_keys(Keys.RETURN)
    time.sleep(1)
    Logging("15c.Input Option 3  successfully")
    btn_done_option_choice = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_done_option_choice"])))
    btn_done_option_choice.click()
    Logging("15.Drag Layout Multiple Choice successfully")
    time.sleep(1)

    single_choice_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["single_choice_from_builder"])))
    editor_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag_2"])))
    webdriver.ActionChains(driver).drag_and_drop(single_choice_from,editor_to).perform()

    time.sleep(1)
    txt_option1_single_choice = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_single_choice_options_1"])))
    txt_option1_single_choice.clear()
    txt_option1_single_choice = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_single_choice_options_1"])))
    txt_option1_single_choice.send_keys(data["menubuilder"]["name_option1_single_choice"])
    Logging("16a.Input Option 1 Single Choice successfully")
    time.sleep(1)
    txt_option1_single_choice.send_keys(Keys.RETURN)
    txt_option2_single_choice = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_single_choice_options_2"])))
    txt_option2_single_choice.send_keys(data["menubuilder"]["name_option2_single_choice"])
    txt_option2_single_choice.send_keys(Keys.RETURN)
    time.sleep(1)
    Logging("16b.Input Option 2 Single Choice successfully")
    txt_option3_single_choice = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_single_choice_options_3"])))
    txt_option3_single_choice.send_keys(data["menubuilder"]["name_option3_single_choice"])
    #txt_option3_single_choice.send_keys(Keys.RETURN)
    Logging("16c.Input Option 3 Single Choice successfully")
    btn_done_option_single_choice = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_done_option_single_choice"])))
    btn_done_option_single_choice.click()
    time.sleep(1)
    Logging("16.Drag Layout Single Choice successfully")

    
    address_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["address_from_builder"])))
    editor_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag"])))
    webdriver.ActionChains(driver).drag_and_drop(address_from,editor_to).perform()
    time.sleep(1)
    check_address_city = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["address_city_from_builder"])))
    check_address_city.click()
    time.sleep(1)
    check_address_state = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["address_state_from_builder"])))
    check_address_state.click()
    time.sleep(1)
    check_address_postal = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["address_postal_from_builder"])))
    check_address_postal.click()
    check_address_country = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["address_country_from_builder"])))
    check_address_country.click()
    Logging("16a.Check City-State-Postal/Zip Code - Country successfully")
    btn_done_option_address = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_done_option_address"])))
    btn_done_option_address.click()
    time.sleep(1)
    Logging("16.Drag Layout Address successfully")
    time.sleep(1)
    editor_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_from_builder"])))
    editor_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag_2"])))
    webdriver.ActionChains(driver).drag_and_drop(editor_from,editor_to).perform()
    time.sleep(1)
    currency_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["currency_from_builder"])))
    editor_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag"])))
    webdriver.ActionChains(driver).drag_and_drop(currency_from,editor_to).perform()
    time.sleep(1)
    select_currency_value_builder = Select(driver.find_element_by_xpath(data["menubuilder"]["list_currency_value"]))
    select_currency_value_builder.select_by_visible_text("VND (₫)")
    Logging("17a.Select Currency value successfully")
    btn_done_option_currency = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_done_option_currency"])))
    btn_done_option_currency.click()
    time.sleep(1)
    Logging("17.Drag Layout Currency successfully")

    number_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["number_from_builder"])))
    editor_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag_2"])))
    webdriver.ActionChains(driver).drag_and_drop(number_from,editor_to).perform()
    Logging("18.Drag Layout Number successfully")
    time.sleep(1)
    
    percent_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["percent_from_builder"])))
    editor_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag"])))
    webdriver.ActionChains(driver).drag_and_drop(percent_from,editor_to).perform()
    Logging("19.Drag Layout Percent successfully")
    time.sleep(1)
    multi_select_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["multi_select_from_builder"])))
    editor_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag_2"])))
    webdriver.ActionChains(driver).drag_and_drop(multi_select_from,editor_to).perform()
    time.sleep(1)
    txt_option1_multi_select = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_multi_select_options_1"])))
    txt_option1_multi_select.clear()
    txt_option1_multi_select = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_multi_select_options_1"])))
    txt_option1_multi_select.send_keys(data["menubuilder"]["name_option1_multi_select"])
    Logging("20a.Input Option 1 Multi-Select successfully")
    txt_option1_multi_select.send_keys(Keys.RETURN)
    txt_option2_multi_select = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_multi_select_select_2"])))
    txt_option2_multi_select.send_keys(data["menubuilder"]["name_option2_multi_select"])
    txt_option2_multi_select.send_keys(Keys.RETURN)
    time.sleep(1)
    Logging("20b.Input Option 2 Multi-Select successfully")
    txt_option3_multi_select = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_multi_select_select_3"])))
    txt_option3_multi_select.send_keys(data["menubuilder"]["name_option3_multi_select"])
    txt_option3_multi_select.send_keys(Keys.RETURN)
    Logging("20c.Input Option 3 Multi-Select successfully")
    btn_done_option_multi_select = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_done_option_multi_select"])))
    btn_done_option_multi_select.click()
    Logging("20.Drag Layout Multi-Select successfully")
    time.sleep(1)

    pick_list_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["pick_list_from_builder"])))
    editor_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag"])))
    webdriver.ActionChains(driver).drag_and_drop(pick_list_from,editor_to).perform()

    time.sleep(1)
    txt_option1_pick_list = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_pick_list_options_1"])))
    txt_option1_pick_list.clear()
    txt_option1_pick_list = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_pick_list_options_1"])))
    txt_option1_pick_list.send_keys(data["menubuilder"]["name_option1_pick_list"])
    Logging("21a.Input Option 1 Pick List successfully")
    txt_option1_pick_list.send_keys(Keys.RETURN)
    txt_option2_pick_list = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_pick_list_select_2"])))
    txt_option2_pick_list.send_keys(data["menubuilder"]["name_option2_pick_list"])
    txt_option2_pick_list.send_keys(Keys.RETURN)
    Logging("21b.Input Option 2 Pick List successfully")
    time.sleep(1)
    txt_option3_pick_list = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_pick_list_select_3"])))
    txt_option3_pick_list.send_keys(data["menubuilder"]["name_option3_pick_list"])
    txt_option3_pick_list.send_keys(Keys.RETURN)
    Logging("21c.Input Option 3 Pick List successfully")
    btn_done_option_pick_list = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_done_option_pick_list"])))
    btn_done_option_pick_list.click()
    time.sleep(1)
    Logging("21.Drag Layout Pick List successfully")
    element = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["org_from_builder"])))
    element.location_once_scrolled_into_view
    time.sleep(2)

    org_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["org_from_builder"])))
    editor_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag_2"])))
    webdriver.ActionChains(driver).drag_and_drop(org_from,editor_to).perform()
    Logging("22.Drag Layout Organization successfully")
    time.sleep(1)
    attachfile_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["attachfile_from_builder"])))
    editor_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag"])))
    webdriver.ActionChains(driver).drag_and_drop(attachfile_from,editor_to).perform()
    Logging("23.Drag Layout Attach files successfully")
    time.sleep(1)
    comment_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["comment_from_builder"])))
    editor_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["editor_to_drag"])))
    webdriver.ActionChains(driver).drag_and_drop(comment_from,editor_to).perform()
    Logging("24.Drag Layout Comments successfully")
    time.sleep(1)
    btn_save_and_close_builder = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_save_and_close"])))
    btn_save_and_close_builder.click()
    time.sleep(6)
    Logging("A. Create Menu successfully")
    driver.refresh()
    time.sleep(4)
    driver.get(domain_name + "/custom_menu")
    time.sleep(2)
    Logging("1. Access Menu Builder successfully")
    
    Logging("-------------- Search Menu Name ------------------")
    click_textbox_search_menu_builder = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["textbox_search_menu_builder"])))
    click_textbox_search_menu_builder.send_keys(data["menubuilder"]["search_menu_name_menu_builder"])
    click_textbox_search_menu_builder.send_keys(Keys.RETURN)
    Logging("1. Search Menu Name successfully")
    time.sleep(5)
    select_a_menu_name = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["select_menu_luuluu"])))
    select_a_menu_name.click()
    Logging("2. Click menu QA Hanbiro successfully")
    WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["loading_dialog"])))
    time.sleep(1)
    if 'Sub QA' in driver.page_source :
        Logging("1.Create Menu => ----------- PASS")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["write_menu"]["pass"])
    else:
        Logging("1.Create Menu => ----------- FAIL")
        ValidateFailResultAndSystem("<div>[Menu Builder]1.Write Menu </div>")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["write_menu"]["fail"])
    '''
    #menu_builder_create = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["show_menu_builder_create"])))
    if 'Sub QA' in driver.page_source :
        Logging("1.Create Menu => ----------- PASS")
    else:
        Logging("1.Create Menu => ----------- FAIL")
        ValidateFailResultAndSystem("<div>[Menu Builder]1.Write Menu </div>")
    '''
    time.sleep(1)
    Logging("-----------------------------Tab Who Can See - Permission------------------------------")
    WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["loading_dialog"])))
    click_setting_builder = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["setting_builder"])))
    click_setting_builder.click()
    Logging("1.Click Settings successfully")
    Logging("-----------------------------Tab Manage Modules - Edit Menu------------------------------")
    WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["loading_dialog"])))
    click_select_tab_manage_modules = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["select_tab_manage_modules"])))
    click_select_tab_manage_modules.click()
    Logging("1.Click Tab Manage Modules successfully")
    click_icon_edit_layout = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["icon_edit_layout"])))
    click_icon_edit_layout.click()
    time.sleep(1)
    Logging("2.Click Icon Edit Layout successfully")
    driver.switch_to.frame(1)
    click_icon_sub_menu_builder = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["click_icon_sub_menu"])))
    click_icon_sub_menu_builder.click()
    select_icon_sub_menu_builder_edit = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["select_icon_sub_menu_edit"])))
    select_icon_sub_menu_builder_edit.click()
    Logging("3.Edit Icon Sub Menu successfully")
    time.sleep(1)
    btn_save_and_close_builder = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_save_and_close"])))
    btn_save_and_close_builder.click()
    time.sleep(3)
    Logging("A. Edit Menu successfully")
    if 'Sub QA' in driver.page_source :
        Logging("1.Edit Menu => ----------- PASS")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["edit_menu"]["pass"])
    else:
        Logging("1.Edit Menu => ----------- FAIL")
        ValidateFailResultAndSystem("<div>[Menu Builder]1.Edit Menu </div>")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["edit_menu"]["fail"])
    
    Logging("-----------------------------Clone Layout------------------------------")
    driver.refresh()
    time.sleep(4)
    click_icon_clone_layout_bd = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["click_icon_clone_layout"])))
    click_icon_clone_layout_bd.click()
    Logging("1.Click icon Clone Layout successfully")
    input_txt_layout_name = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_layout_name"])))
    input_txt_layout_name.send_keys(data["menubuilder"]["name_clone_layout"])
    Logging("2.Input Clone Layout successfully")
    time.sleep(1)
    click_btn_save_clone_layout = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_save_clone_layout"])))
    click_btn_save_clone_layout.click()
    Logging("A. Clone Layout successfully")
    time.sleep(3)
    if 'Sub QA 2' in driver.page_source :
        Logging("1.Clone Layout => -------------- PASS")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["clone_layout"]["pass"])
    else:
        Logging("1.Clone Layout => -------------- FAIL")
        ValidateFailResultAndSystem("<div>[Menu Builder]1.Clone Layout</div>")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["clone_layout"]["fail"])
    Logging("-----------------------------Add Folder------------------------------")
    click_btn_add_folder = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_add_folder"])))
    click_btn_add_folder.click()
    Logging("1.Click button Add Folder successfully")
    input_txt_folder_name = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_folder_name"])))
    input_txt_folder_name.send_keys(data["menubuilder"]["folder_name"])
    Logging("2.Input Folder Name successfully")
    click_btn_save_add_folder = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_save_add_folder"])))
    click_btn_save_add_folder.click()
    Logging("3.Click button Save successfully")
    Logging("A. Add Folder successfully")
    time.sleep(2)
    if 'Folder QA' in driver.page_source :
        Logging("1.Add Folder => ------------ PASS")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["add_folder"]["pass"])
    else:
        Logging("1.Add Folder => ------------ FAIL")
        ValidateFailResultAndSystem("<div>[Menu Builder]Add Folder</div>")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["add_folder"]["fail"])
    Logging("-----------------------------Edit Folder------------------------------")
    click_folder_name = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["edit_name_folder"])))
    click_folder_name.click()
    Logging("1.Click Folder successfully")
    input_edit_folder_name = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_edit_name_folder"])))
    input_edit_folder_name.send_keys(data["menubuilder"]["name_folder_edit"])
    input_edit_folder_name.send_keys(Keys.RETURN)
    Logging("2.Edit Folder Name successfully")
    Logging("A. Edit Name Folder successfully")
    time.sleep(3)
    if 'Folder Builder' in driver.page_source :
        Logging("1.Edit Folder => --------- PASS")
    else:
        Logging("1.Edit Folder => ---------  FAIL")

    Logging("-----------------------------Delete  Folder------------------------------")
    driver.refresh()
    time.sleep(4)
    #WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["loading_dialog"])))
    #access_menu_home = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["screen_home_gw"])))
    #access_menu_home.click()
    #driver.get(domain_name + "/custom_menu")
    #select_a_menu_name = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["select_menu_luuluu"])))
    #select_a_menu_name.click()
    #time.sleep(2)
    #Logging("1. Click menu QA Hanbiro successfully")
    #click_setting_builder = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["setting_builder"])))
    #click_setting_builder.click()
    click_icon_delete_folder = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["icon_delete_folder_bd"])))
    click_icon_delete_folder.click()
    time.sleep(1)
    Logging("1.Click icon Delete successfully")
    click_btn_ok_delete_folder = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_ok_delete"])))
    click_btn_ok_delete_folder.click()
    Logging("A. Delete Folder successfully")
    time.sleep(2)
    if 'Folder Builder' in driver.page_source :
        Logging("1.Delete  Folder => ---------FAIL")
    else:
        Logging("1.Delete  Folder => ---------PASS")
    
    Logging("-----------------------------Export Layout------------------------------")
        
    click_icon_export_layout = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["icon_export_layout"])))
    click_icon_export_layout.click()
    if 'json' in driver.page_source :
        Logging("Export Layout successfully =>------ PASS")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["export_layout"]["pass"])
    else:
        Logging("Export Layout fail =>------- FAIL")
        ValidateFailResultAndSystem("<div>[Menu Builder]Export Layout fail</div>")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["export_layout"]["fail"])

    Logging("-----------------------------Mode View------------------------------")
    driver.refresh()
    time.sleep(4)    
    click_icon_mode_view = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["icon_mode_view"])))
    click_icon_mode_view.click()
    time.sleep(1)
    Logging("1.Click icon Mode View successfully")
    show_calendar_view_on = WebDriverWait(driver, 30).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["show_date_turn_on_calenda_view"])))
    if show_calendar_view_on.is_displayed():
        Logging("=> Calendar View ON")
    else:
        turn_on_calendar_view = WebDriverWait(driver, 30).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["turn_on_calenda_view"])))
        turn_on_calendar_view.click()
        time.sleep(1)  
        Logging("2.Turn On/Off Calendar View successfully")
    click_btn_save_calendar_view = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_save_calendar_view"])))
    click_btn_save_calendar_view.click()
    driver.refresh()
    time.sleep(2) 
    click_icon_mode_view = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["icon_mode_view"])))
    click_icon_mode_view.click()
    time.sleep(3)
    Logging("A. Mode View Calendar View successfully")
    if 'Calendar View' in driver.page_source :
        Logging(" Mode View =>--------- PASS")
    else:
        Logging("Mode View =>---------- FAIL")
    click_btn_save_calendar_view = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_save_calendar_view"])))
    click_btn_save_calendar_view.click()
    time.sleep(1)
    


    '''
    Logging("-----------------------------Alert/Warning Settings------------------------------")
    driver.refresh()
    time.sleep(4)      
    click_icon_alert = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["icon_alert"])))
    click_icon_alert.click()
    Logging("1.Click Icon Alert/Warning Settings successfully")
    select_value_do_not_use = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["select_do_not_use"])))
    select_value_do_not_use.click()
    Logging("2.Select Value Do Not Use successfully")
    if 'Alert/Warning Settings' in driver.page_source :
        Logging(" Alert/Warning Settings =>--------- PASS")
    else:
        Logging("Alert/Warning Settings =>---------- FAIL")
        ValidateFailResultAndSystem("<div>[Menu Builder]Alert/Warning Settings</div>")
   
    click_btn_save_alert = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_save_alert"])))
    click_btn_save_alert.click()
    Logging("A. Select Alert/Warning Settings successfully")
    '''





    Logging("-----------------------------Import Layout------------------------------")
    driver.refresh()
    time.sleep(4)  
    click_btn_add_module = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_add_module_layout"])))
    click_btn_add_module.click()
    time.sleep(1)
    driver.switch_to.frame(1)
    Logging("2.Click button Add Module successfully")
    click_button_import_layout = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_import_layout"])))
    click_button_import_layout.click()
    Logging("3. Click button IMPORT LAYOUT successfully")
    select_layout_import = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["select_layout_import"])))
    select_layout_import.click()
    Logging("4. Select Layout successfully")
    time.sleep(2)
    btn_ok_import = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_ok_import_layout"])))
    btn_ok_import.click()
    Logging("5.Click button OK successfully")
    time.sleep(1)
    txt_sub_menu_name_import = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_sub_menu_name"])))
    txt_sub_menu_name_import.send_keys(data["menubuilder"]["menu_sub_import"])
    Logging("5. Input Sub Menu Name Builder  successfully")
    btn_save_and_close_builder = WebDriverWait(driver, 30).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_save_and_close"])))
    btn_save_and_close_builder.click()
    time.sleep(2)
    driver.refresh()
    time.sleep(4)
    WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["loading_dialog"])))
    Logging("A. Import Layout Menu Builder successfully")
    time.sleep(3)
    if 'Import Layout' in driver.page_source :
        Logging(" Import Layout =>----------- PASS")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["import_layout"]["pass"])
    else:
        Logging("Import Layout =>------------ FAIL")
        ValidateFailResultAndSystem("<div>[Menu Builder]Import Layout</div>")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["import_layout"]["fail"])

    Logging("-----------------------------Delete Layout------------------------------")
    driver.refresh()
    time.sleep(4)  
    click_setting_builder = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["setting_builder"])))
    click_setting_builder.click()
    Logging("1.Click Settings successfully")
    click_icon_delete_layout = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["icon_delete_layout"])))
    click_icon_delete_layout.click()
    Logging("1.Click icon Delete successfully")
    click_btn_ok_delete_layout = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_ok_delete"])))
    click_btn_ok_delete_layout.click()
    Logging("A. Delete Layout successfully")
    time.sleep(3)
    if 'Import Layout' in driver.page_source :
        Logging(" Delete Layout => --------------- FAIL")
        ValidateFailResultAndSystem("<div>[Menu Builder]Delete Layout</div>")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["delete_layout"]["fail"])
    else:
        Logging("Delete Layout => --------------- PASS")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["delete_layout"]["pass"])
time.sleep(1)    

def write_layout_menubuilder(domain_name):

    access_menu_home = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["screen_home_gw"])))
    access_menu_home.click()
    WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["loading_dialog"])))
    time.sleep(2)
    driver.get(domain_name + "/custom_menu/list/")
    #access_menu_menu_builder = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["menu_builder"])))
    #access_menu_menu_builder.click()
    time.sleep(2)
    Logging("1. Access Menu Builder successfully")
    Logging("-------------- Search Menu Name ------------------")
    click_textbox_search_menu_builder = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["textbox_search_menu_builder"])))
    click_textbox_search_menu_builder.send_keys(data["menubuilder"]["search_menu_name_menu_builder"])
    click_textbox_search_menu_builder.send_keys(Keys.RETURN)
    Logging("1. Search Menu Name successfully")
    time.sleep(1)
    select_a_menu_name = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["select_menu_luuluu"])))
    select_a_menu_name.click()
    time.sleep(1)
    Logging("2. Click menu QA Hanbiro successfully")
    if 'Sub QA' in driver.page_source :
        Logging("1.Acess Menu => ----------- PASS")
    else:
        Logging("1.Acess Menu => ----------- FAIL")
    Logging("--------------------- Create Layout  ---------------------")
    try:
        click_btn_close_clock_in = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_close_clock_in"])))
        click_btn_close_clock_in.click()
    except WebDriverException:
        Logging("Not show Clock In")
    time.sleep(1)
    select_a_fd_sub_2 = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["select_sub_2"])))
    select_a_fd_sub_2.click()
    click_button_create = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["button_create_title"])))
    click_button_create.click()
    Logging("1. Click Create successfully")
    click_textbox_name_menu_builder = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["textbox_name_builder"])))
    click_textbox_name_menu_builder.send_keys(data["menubuilder"]["name_layout"])
    time.sleep(1)
    title_layout_name=click_textbox_name_menu_builder.get_attribute("value")
    if(title_layout_name==data["menubuilder"]["name_layout"]):
        Logging("=> Input Name Layout =>pass")
    else:
        Logging("=> Input Name Layout =>fail")
    Logging("2. Input Name Layout successfully" + " :  " + data["menubuilder"]["name_layout"])
    select_multiple = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["multiple_choice"])))
    select_multiple.click()
    Logging("6. Select Multiple successfully")
    time.sleep(1)
    click_textbox_currency = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_currency"])))
    click_textbox_currency.send_keys(data["menubuilder"]["input_currency"])
    Logging("8. Input Currency successfully" + " :  " + data["menubuilder"]["input_currency"])
    time.sleep(1)
    click_pick_list = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["click_pick_list"])))
    click_pick_list.send_keys(data["menubuilder"]["name_search_pick_list"])
    click_pick_list.send_keys(Keys.RETURN)
    Logging("10. Select Pick List successfully")
    time.sleep(1)
    click_textbox_url = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["textbox_url"])))
    click_textbox_url.send_keys(data["menubuilder"]["name_url"])
    Logging("4. Input URL successfully" + " :  " + data["menubuilder"]["name_url"])
    click_textbox_single_line = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["textbox_single_line"])))
    click_textbox_single_line.send_keys(data["menubuilder"]["name_single_line"])
    Logging("3. Input Name Single Line successfully"  + " :  " + data["menubuilder"]["name_single_line"])
    click_textbox_phone = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["textbox_phone"])))
    click_textbox_phone.send_keys(data["menubuilder"]["number_phone"])
    Logging("5. Input Phone successfully" + " :  " + data["menubuilder"]["number_phone"])
    time.sleep(1)
    click_textbox_address = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_address"])))
    click_textbox_address.send_keys(data["menubuilder"]["name_address"])
    click_textbox_address_2 = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_address_2"])))
    click_textbox_address_2.send_keys(data["menubuilder"]["name_address_2"])
    Logging("7. Input Address successfully" + " :  " + data["menubuilder"]["name_address"]+ data["menubuilder"]["name_address_2"])
    time.sleep(1)
    click_textbox_percent = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_percent"])))
    click_textbox_percent.send_keys(data["menubuilder"]["input_percent"])
    Logging("9. Input Phone successfully" + " :  " + data["menubuilder"]["input_percent"])
    time.sleep(1)
    driver.execute_script("window.scrollTo(100, 0)")
    time.sleep(1)
    click_txt_multi_line = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_multi_line"])))
    click_txt_multi_line.click()
    click_txt_multi_line.send_keys(data["menubuilder"]["content_multi_line"])
    Logging("13. Input Multi-Line successfully")
    time.sleep(1)
    editor_frame = driver.find_element_by_class_name("tox-edit-area__iframe")
    driver.switch_to.frame(editor_frame)
    input_editor = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["input_editor"])))
    input_editor.send_keys(data["menubuilder"]["editor_content"])
    Logging("17. Input Editor successfully")
    time.sleep(1)
    driver.switch_to.default_content()
    click_multi_select = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_multi_select"])))
    click_multi_select.send_keys(data["menubuilder"]["search_multi_select"])
    click_multi_select.send_keys(Keys.RETURN)
    time.sleep(1)
    Logging("19. Select Multi-Select successfully")
    click_textbox_mail = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_email"])))
    click_textbox_mail.send_keys(data["menubuilder"]["input_email"])
    Logging("11. Input Mail successfully" + " :  " + data["menubuilder"]["input_email"])
    time.sleep(1)
    click_date_range_from = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["click_date_range_from"])))
    click_date_range_from.click()
    time.sleep(1)
    select_date_range_from =  WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["select_date_range_from"])))
    select_date_range_from.click()
    time.sleep(1)
    Logging("14. Select Date Range From successfully")
    click_date_range_to = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["click_date_range_to"])))
    click_date_range_to.click()
    time.sleep(1)
    select_date_range_to=  WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["select_date_range_to"])))
    select_date_range_to.click()
    Logging("15. Select Date Range To successfully")
    time.sleep(1)
    driver.execute_script("window.scrollTo(100, 0)")
    get_file = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["click_add_file"])))
    get_file.send_keys(luu_function.file_img)
    time.sleep(2)
    Logging("21. Attach file successfully")
    click_btn_save_builder = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_save_menu_builder"])))
    click_btn_save_builder.click()
    time.sleep(4)
    Logging("22.Save Layout successfully")
    Logging("A. Create Layout successfully")
    time.sleep(3)
    if 'Luu Luu 01' in driver.page_source :
        Logging("1.Create Layout => -------------- PASS")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["create_data"]["pass"])
    else:
        Logging("1.Create Layout => -------------- FAIL")
        ValidateFailResultAndSystem("<div>[Menu Builder]1.Create Layout</div>")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["create_data"]["fail"])
    time.sleep(1)
    Logging("--------------------- View and Comment  ---------------------")
    click_btn_back_builder = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_back_builder"])))
    click_btn_back_builder.click()
    time.sleep(1)
    select_title_builder = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["select_title"])))
    select_title_builder.click()
    write_comment = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_comment_builder"])))
    write_comment.click()
    input_comment = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["input_coment"])))
    input_comment.send_keys(data["menubuilder"]["content_comment"])
    btn_save_comment_builder = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_save_comment"])))
    btn_save_comment_builder.click()
    time.sleep(1)
    Logging("A. Save comment successfully")
    driver.execute_script("window.scrollTo(0, 100)")
    time.sleep(3)
    if 'Hello' in driver.page_source :
        Logging("1.View and Comment => ---------  PASS")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["view_and_comment"]["pass"])
    else:
        Logging("1.View and Comment => --------- FAIL")
        ValidateFailResultAndSystem("<div>[Menu Builder]View and Comment</div>")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["view_and_comment"]["fail"])

    Logging("--------------------- Import Menu Builder  ---------------------")
    click_btn_back_builder = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_back_builder"])))
    click_btn_back_builder.click()
    driver.refresh()
    time.sleep(3)
    click_btn_more = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_more"])))
    click_btn_more.click()
    click_btn_import = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["import_file"])))
    click_btn_import.click()
    select_file = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["add_file"])))
    select_file.send_keys(luu_function.file_buildr)
    Logging("1.Select File successfully")
    time.sleep(2)
    click_btn_upload = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_upload"])))
    click_btn_upload.click()
    time.sleep(1)
    click_value_name = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_select_name"])))
    click_value_name.send_keys(data["menubuilder"]["name_search"])
    click_value_name.send_keys(Keys.RETURN)
    time.sleep(2)
    Logging("2.Select Name successfully")
    click_value_create_date = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_create_date"])))
    click_value_create_date.send_keys(data["menubuilder"]["create_date_search"])
    click_value_create_date.send_keys(Keys.RETURN)
    Logging("3.Select Created Date successfully")
    time.sleep(1)
    click_value_single_line = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_single_line"])))
    click_value_single_line.send_keys(data["menubuilder"]["single_line_search"])
    click_value_single_line.send_keys(Keys.RETURN)
    Logging("4.Select Single Line successfully")
    time.sleep(1)
    click_value_email = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_value_email"])))
    click_value_email.send_keys(data["menubuilder"]["email_search"])
    click_value_email.send_keys(Keys.RETURN)
    Logging("5.Select Value Email successfully")
    time.sleep(1)
    click_value_url = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_value_url"])))
    click_value_url.send_keys(data["menubuilder"]["url_search"])
    click_value_url.send_keys(Keys.RETURN)
    Logging("6.Select Value URL successfully")
    time.sleep(1)
    click_value_date = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_value_date"])))
    click_value_date.send_keys(data["menubuilder"]["date_search"])
    click_value_date.send_keys(Keys.RETURN)
    Logging("7.Select Date successfully")
    time.sleep(1)
    click_value_date_time = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_value_date_time"])))
    click_value_date_time.send_keys(data["menubuilder"]["date_time_search"])
    click_value_date_time.send_keys(Keys.RETURN)
    Logging("8.Select Date Time successfully")
    time.sleep(1)
    click_value_date_range = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_value_date_range"])))
    click_value_date_range.send_keys(data["menubuilder"]["date_range_search"])
    click_value_date_range.send_keys(Keys.RETURN)
    Logging("9.Select Date Range successfully")
    time.sleep(1)
    click_value_phone = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_value_phone"])))
    click_value_phone.send_keys(data["menubuilder"]["phone_search"])
    click_value_phone.send_keys(Keys.RETURN)
    Logging("10.Select Phone successfully")
    time.sleep(1)
    click_value_line = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_value_multi_line"])))
    click_value_line.send_keys(data["menubuilder"]["multi_line_search"])
    click_value_line.send_keys(Keys.RETURN)
    Logging("11.Select Multi Line  successfully")
    time.sleep(1)
    click_value_choice = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_value_multiple_choice"])))
    click_value_choice.send_keys(data["menubuilder"]["multiple_choice_search"])
    click_value_choice.send_keys(Keys.RETURN)
    Logging("12.Select Multiple Choice successfully")
    time.sleep(1)
    click_value_sng_choice = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_value_single_choice"])))
    click_value_sng_choice.send_keys(data["menubuilder"]["single_choice_search"])
    click_value_sng_choice.send_keys(Keys.RETURN)
    Logging("13.Select Single Choice successfully")
    time.sleep(1)
    click_value_address = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_value_address"])))
    click_value_address.send_keys(data["menubuilder"]["address_search"])
    click_value_address.send_keys(Keys.RETURN)
    Logging("14.Select Address successfully")
    time.sleep(1)
    click_value_currency = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_value_currency"])))
    click_value_currency.send_keys(data["menubuilder"]["currency_search"])
    click_value_currency.send_keys(Keys.RETURN)
    Logging("15.Select Currency successfully")
    click_value_number = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_value_number"])))
    click_value_number.send_keys(data["menubuilder"]["number_search"])
    click_value_number.send_keys(Keys.RETURN)
    Logging("16.Select Number successfully")
    time.sleep(1)
    click_value_percent = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_value_percent"])))
    click_value_percent.send_keys(data["menubuilder"]["percent_search"])
    click_value_percent.send_keys(Keys.RETURN)
    Logging("17.Select Percent successfully")
    time.sleep(1)
    click_value_multi_select = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_value_multi_select"])))
    click_value_multi_select.send_keys(data["menubuilder"]["multi_select_search"])
    click_value_multi_select.send_keys(Keys.RETURN)
    Logging("18.Select Multi Select successfully")
    time.sleep(1)
    click_value_pick_list = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_value_pick_list"])))
    click_value_pick_list.send_keys(data["menubuilder"]["pick_list_search"])
    click_value_pick_list.send_keys(Keys.RETURN)
    Logging("19.Select Pick List successfully")
    time.sleep(1)
    click_btn_save_import = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_save_import"])))
    click_btn_save_import.click()
    time.sleep(2)
    click_btn_back_import = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_back_import"])))
    click_btn_back_import.click()
    time.sleep(4)
    Logging("A. Import successfully")
    if 'Luu Luu 03' in driver.page_source :
        Logging("1. Import Menu Builder =>--------  PASS")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["import_data"]["pass"])
    else:
        Logging("1.Import Menu Builder =>---------  FAIL")
        ValidateFailResultAndSystem("<div>[Menu Builder]Import Menu Builder</div>")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["import_data"]["fail"])
    time.sleep(1)
    Logging("--------------------- Search Menu Builder  ---------------------")
    driver.refresh()
    time.sleep(8)
    Logging("--------- a. Search All --------- ")
    click_list_search_field = WebDriverWait(driver, 30).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["click_list_search_field"])))
    click_list_search_field.click()
    Logging("1.Click List Search Field successfully")
    time.sleep(2)
    click_txt_search_layout = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_search_keyword_all"])))
    click_txt_search_layout.send_keys(data["menubuilder"]["name_search_all"])
    click_txt_search_layout.send_keys(Keys.RETURN)
    Logging("2.Input value successfully")
    time.sleep(3)   
    if 'Total 1' in driver.page_source :
        Logging("Search Menu Builder =>----- PASS")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["search_data"]["pass"])
    else:
        Logging("Search Menu Builder =>----- FAIL")
        ValidateFailResultAndSystem("<div>[Menu Builder]SEARCH</div>")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["search_data"]["fail"])
    
    Logging("--------------------- Export Menu Builder  ---------------------")
    click_btn_more = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_more"])))
    click_btn_more.click()
    Logging("1.Click button More  successfully")
    click_export_builder = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["select_export"])))
    click_export_builder.click()
    Logging("2.Click Export successfully")
    click_select_all = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["click_select_all"])))
    click_select_all.click()
    Logging("3.Select All successfully")
    click_btn_export_data = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_export"])))
    click_btn_export_data.click()    
    Logging("A. Export successfully")
    time.sleep(1)
    if 'form' in driver.page_source :
        Logging("1. EXPORT =>----------- PASS")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["export_data"]["pass"])
    else:
        Logging("1. EXPORT =>----------- FAIL")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["export_data"]["fail"])
      
    Logging("--------------------- Mark as Read  ---------------------")
    click_btn_mark_as_read = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_mark_as_read"])))
    click_btn_mark_as_read.click()
    time.sleep(1)
    Logging("1.Click icon Mark as Read  successfully")
    WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["loading_dialog"])))
    Logging("A. Mark as Read successfully")
    time.sleep(5)
    if 'Total 2' in driver.page_source :
        Logging("Mark as Read =>----- PASS")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["mark_as_read"]["pass"])
    else:
        Logging("Mark as Read =>----- FAIL")
        ValidateFailResultAndSystem("<div>[Menu Builder]Mark as Read</div>")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["mark_as_read"]["fail"])

    Logging("--------------------- Download All Attachments  ---------------------")
    click_btn_download_all_file = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_download_all_file"])))
    click_btn_download_all_file.click()
    Logging("1.Click icon Download All Attachments  successfully")
    WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["loading_dialog"])))
    time.sleep(2)
    if 'custom' in driver.page_source :
        Logging("Download All Attachments =>----- PASS")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["download_all_attachment"]["pass"])
    else:
        Logging("Download All Attachments =>----- FAIL")
        ValidateFailResultAndSystem("<div>[Menu Builder]Download All Attachments Fail</div>")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["download_all_attachment"]["fail"])
    Logging("--------------------- Download File  ---------------------")
    select_title_layout = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["select_title_download"])))
    select_title_layout.click()
    Logging("1.Select Title successfully")
    click_icon_download_file = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["icon_download_file_layout"])))
    click_icon_download_file.click()
    Logging("2.Click icon Download file  successfully")
    time.sleep(2)
    if 'Hoa hong 4' in driver.page_source :
        Logging("Download File => ---------- PASS")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["download_file"]["pass"])
    else:
        Logging("Download File => ---------- FAIL")
        ValidateFailResultAndSystem("<div>[Menu Builder]Download File</div>")
        TestCase_LogResult(**data["testcase_result"]["menubuilder"]["download_file"]["fail"])
    
    Logging("--------------------- Copy-Past  ---------------------")
    try:
        click_btn_more = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_more_copy"]))).click()
        time.sleep(1)
        select_value_copy = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["value_copy_data"])))
        select_value_copy.click()
        time.sleep(1)
        btn_close_copy = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_close_copy_data"])))
        btn_close_copy.click()
        time.sleep(1)
        
        try:
            click_btn_close_clock_in = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_close_clock_in"])))
            click_btn_close_clock_in.click()
        except WebDriverException:
            Logging("Not show Clock In")

        time.sleep(1)

        click_button_create = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["button_create_title"])))
        click_button_create.click()
        Logging("1. Click Create successfully")
        time.sleep(1)
        click_button_paste = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_paste_copy_data"])))
        click_button_paste.click()
        time.sleep(1)
        driver.refresh()
        time.sleep(8)
        '''
        try:
            click_btn_close_clock_in = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_close_clock_in"])))
            click_btn_close_clock_in.click()
        except WebDriverException:
            Logging("Not show Clock In")
        '''
        Logging("2. Click button Past successfully")
        click_textbox_name_menu_builder = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["textbox_name_builder"])))
        click_textbox_name_menu_builder.clear()
        click_textbox_name_menu_builder.send_keys(data["menubuilder"]["title_copy"])
        Logging("3. Input Name Menu Builder  successfully")
        click_btn_save_builder = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_save_menu_builder"])))
        click_btn_save_builder.click()
        time.sleep(4)
        Logging("SAVE SAVE SAVE => ---------- PASS")
    except WebDriverException:
        Logging("Can not copy/paste")
    time.sleep(1)
    Logging("--------------------- View Timeline  ---------------------")
    click_btn_timeline = WebDriverWait(driver, 30).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_timeline"])))
    click_btn_timeline.click()
    btn_back_timeline = WebDriverWait(driver, 30).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_back_timeline"])))
    time.sleep(1)
    if btn_back_timeline.is_displayed():
        Logging("=> View Timeline  =>--------- PASS")
    else:
        Logging("=> View Timeline =>---------- FAIL")
    time.sleep(1)
    
    Logging("--------------------- Delete layout Name ---------------------")
    driver.refresh()
    time.sleep(8)
    try:
        click_btn_close_clock_in = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_close_clock_in"])))
        click_btn_close_clock_in.click()
    except WebDriverException:
        Logging("Not show Clock In")
    click_btn_more = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_more_copy"])))
    click_btn_more.click()
    time.sleep(2)
    select_value_del = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_delete_layout_user"])))
    select_value_del.click()
    time.sleep(3)
    Logging("Delete layout Name=> ---------- PASS")


    '''
    Logging("--------------------- Calendar View  ---------------------")
    try:
        click_icon_calendar_view = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["icon_calendar_view"])))
        click_icon_calendar_view.click()   
        time.sleep(5)
        if 'Lunar' in driver.page_source :
            Logging("Calendar View => ---------- PASS")
        else:
            Logging("Calendar View => ---------- FAIL")
        click_icon_list_view = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["icon_list_view"])))
        click_icon_list_view.click()   
        time.sleep(3)
    except WebDriverException:
        Logging("Not show Calendar View")
    '''

def delete_menubuilder(domain_name):
    
    Logging("------------------------------------------------------D. Delete Menu ------------------------------------------------------")
    access_menu_home = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["screen_home_gw"])))
    access_menu_home.click()
    WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["loading_dialog"])))
    driver.get(domain_name + "/custom_menu")
    time.sleep(2)
    Logging("1. Access Menu Builder successfully")
    click_textbox_search_menu_builder = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["textbox_search_menu_builder"])))
    click_textbox_search_menu_builder.send_keys(data["menubuilder"]["search_menu_name_menu_builder"])
    click_textbox_search_menu_builder.send_keys(Keys.RETURN)
    Logging("1. Search Menu Name successfully")
    time.sleep(1)
    try:
        click_icon_delete_folder = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["click_btn_delete_menu"])))
        click_icon_delete_folder.click()
        time.sleep(1)
        Logging("8. Click icon Delete successfully")
        check_force_delete = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["check_force_delete"])))
        check_force_delete.click()
        Logging("9. Check Force Delete successfully")
        txt_securerity_pw = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["txt_input_pw_delete"])))
        txt_securerity_pw.send_keys(data["menubuilder"]["name_pw_delete"])
        Logging("10. Input Password successfully")
        click_btn_ok_delete = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["btn_ok_delete_menubd"])))
        click_btn_ok_delete.click()
        Logging("A. Delete Menu Builder successfully")
        time.sleep(3)
        if 'Total 0' in driver.page_source :
            Logging("DELETE MENU => ------ PASS")
            TestCase_LogResult(**data["testcase_result"]["menubuilder"]["delete_menu"]["pass"])
        else:
            Logging("DELETE MENU => ------- FAIL")
            TestCase_LogResult(**data["testcase_result"]["menubuilder"]["delete_menu"]["fail"])
    except WebDriverException:
            Logging("Not show Menu builder")
    access_menu_home = WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.XPATH, data["menubuilder"]["screen_home_gw"])))
    access_menu_home.click()
    
   
    
    jpg = glob.glob(os.path.join("Downloads\\*.jpg"))
    for image in jpg:
        os.remove(image)
    json = glob.glob(os.path.join("Downloads\\*.json"))
    for item in json:
        os.remove(item)
    files = glob.glob(os.path.join("Downloads\\*.xls"))
    for file in files:
        os.remove(file)
    filezip = glob.glob(os.path.join("Downloads\\*.zip"))
    for zipbd in filezip:
        os.remove(zipbd)
    
    
def admin_menu_menubuilder(domain_name):
    admin = CheckPresenceOfAdminsubmenu(domain_name)
    if admin == True:
        try:
            admin_write_menubuilder(domain_name)
            Logging("create Menu Builder successfully")
        except WebDriverException:
            Logging("fail to create folder")
        
    else:
        Logging("1.Create Menu Builder => Account is not admin")


def write_menu_menubuilder(domain_name):
    admin = CheckPresenceOfAdminsubmenu(domain_name)
    if admin == True:
        try:
            write_layout_menubuilder(domain_name)
            Logging("create Menu Builder successfully")
        except WebDriverException:
            Logging("fail to create folder")
        
    else:
        Logging("2.Create Menu Builder => Account is not admin")

    if admin == True:
        try:
            delete_menubuilder(domain_name)
            Logging("Delete Menu Builder successfully")
        except WebDriverException:
            Logging("Delete Menu Builder Fail")
        
    else:
        Logging("Delete => Account is not admin")
    




def is_Displayed(driver,xpath):
    try:
        driver.find_elements_by_xpath(xpath)
    except NoSuchElementException:
        return False
    return True
    
def so(total):
    num = re.sub(r'\D', "", total)
    return int(num)


'''
with open(local+'\\'+'luu_builder.txt','w') as builder:
    domain="http://qa.hanbiro.net"
    admin_menu_menubuilder(domain,builder)       
    write_menu_menubuilder(domain,builder)   


result=open(local+'\\result.txt','r')
file_result=result.read()
Logging(file_result)
'''






